sonar.projectKey=DeshanJayasinghe_user-service
sonar.organization=deshanjayasinghe
sonar.java.coveragePlugin=jacoco
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
