sonar.projectKey=DeshanJayasinghe_micro-service-student-management-system-user-service
sonar.organization=deshanjayasinghe
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes
